### PR TITLE
Access to Sound#valueOf method through Reflection to avoid java.lang IncompatibleClassChangeError when using versions prior to 1.21.3

### LINKED ISSUE #157: java.lang.IncompatibleClassChangeError: Method 'org.bukkit.Sound org.bukkit.Sound.valueOf(java.lang.String)' must be Methodref constant
I am seeing this error since I tried to use the latest development version (DeluxeMenus-1.14.1-DEV-PR--abd23c94.jar). I think it may be due to the change of the org.bukkit.Sound class type from Enum to Interface.
```
[01Dec2024 01:19:32.853] [Server thread/WARN] [DeluxeMenus/]: Task #6971 for DeluxeMenus v1.14.1-DEV-PR--abd23c94 generated an exception
java.lang.IncompatibleClassChangeError: Method 'org.bukkit.Sound org.bukkit.Sound.valueOf(java.lang.String)' must be Methodref constant
	at com.extendedclip.deluxemenus.action.ClickActionTask.run(ClickActionTask.java:363) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[arclight:arclight-1.16.5-1.0.26-SNAPSHOT-5c6b7953]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftSchedulerMixin.java:400) ~[arclight:arclight-1.16.5-1.0.26-SNAPSHOT-5c6b7953]
	at net.minecraft.server.MinecraftServer.handler$bcc000$arclight$runScheduler(MinecraftServerMixin.java:2160) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServerMixin.java) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServerMixin.java:291) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServerMixin.java:787) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1917) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

### PR DESCRIPTION
**Pull request by MemencioPerez**
Seems to fix #157

### CODE REVIEW

**Comment by Tanguygab** [comment]
I think it'd just be better if we finally switched to the method with a String parameter for the sound, that way custom sounds can finally be used. https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/Player.html#playSound(org.bukkit.Location,java.lang.String,float,float)

File: src/main/java/com/extendedclip/deluxemenus/utils/SoundUtils.java [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+
+public class SoundUtils {
+
+    public static Sound getSound(String name) {
+        try {
+            // As of Minecraft 1.21.3, the org.bukkit.Sound class type changed from Enum to Interface.
+            // This fixes java.lang.IncompatibleClassChangeError when trying to use versions prior to 1.21.3.
+            Method valueOfMethod = Class.forName("org.bukkit.Sound").getMethod("valueOf", String.class);
+            return (Sound) valueOfMethod.invoke(null, name);
+        } catch (Exception e) {
```
Comment (BlitzOffline) [inline src/main/java/com/extendedclip/deluxemenus/utils/SoundUtils.java:15]: If we know an IncompatibleClassChangeError will be thrown, we should catch it instead of a general catch.

Catching like this might hide future issues.

**Review by BlitzOffline — CHANGES_REQUESTED** [review]

File: src/main/java/com/extendedclip/deluxemenus/utils/SoundUtils.java (hunk 1 above)
Comment (MemencioPerez) [reply src/main/java/com/extendedclip/deluxemenus/utils/SoundUtils.java:15]: An IncompatibleClassChangeException will not be thrown since the valueOf method is being called using Reflection, possible exceptions are ClassNotFoundException, NoSuchMethodException, IllegalAccessException, and InvocationTargetException.

**Review by BlitzOffline — APPROVED** [review]

**Review by Kqliber — APPROVED** [review]
