### PR TITLE
fix: item flags not working in 1.20.5+ & deprecate hide_ options

### LINKED ISSUE #115: Item options does not work in 1.21
### description
hide_enchantments: true
hide_attributes: true
I only used the above options.
They don't work properly in version 1.21.
Others have not been tested yet.
### DeluxeMenus version:
1.14.1-DEV-181
### Server Version
Paper version 1.21-27-master@76c2f16

### LINKED ISSUE #116: Hide attributes doesn't work on 1.20.6
`hide_attributes: true` doesn't work well on 1.20.6 server.
I'm using Purpur server, and using DeluxeMenus 1.14.1-DEV-179.

it doesn't hide armor stats like:
```
When on head:
+2 armor
```

### PR DESCRIPTION
**Pull request by iGabyTM**
This PR fixes the following issues:
- Fix #115
- Fix #116 
It also deprecates the `hide_(attributes/enchantments/unbreakable)` item options in favor of `item_flags`. Users will receive a warning message in console
> Option 'hide_unbreakable' of item 'aaa' in menu 'basics_menu' is deprecated and will be removed in the future. Replace it with item_flags: [HIDE_UNBREAKABLE].

I've also improved the _unknown requirement type_ warning by also printing the value from config for easier debug.

### CODE REVIEW

**Review by darbyjack — APPROVED** [review]

File: src/main/java/com/extendedclip/deluxemenus/menu/options/MenuItemOptions.java [hunk 1]
```diff
@@ -512,8 +491,8 @@ public MenuItemOptionsBuilder bannerMeta(final @NotNull List<Pattern> bannerMeta
             return this;
         }
 
-        public MenuItemOptionsBuilder itemFlags(final @NotNull List<ItemFlag> itemFlags) {
```
Comment (BlitzOffline) [inline src/main/java/com/extendedclip/deluxemenus/menu/options/MenuItemOptions.java:515]: Small thing, and we can deal with this if we ever have to, but there's no way to remove an item flag.

**Review by BlitzOffline — APPROVED** [review]

File: src/main/java/com/extendedclip/deluxemenus/menu/options/MenuItemOptions.java (hunk 1 above)
Comment (iGabyTM) [reply src/main/java/com/extendedclip/deluxemenus/menu/options/MenuItemOptions.java:515]: It wasn't before either. What do you suggest?

Comment (iGabyTM) [reply src/main/java/com/extendedclip/deluxemenus/menu/options/MenuItemOptions.java:515]: @BlitzOffline would this work?
Two `Set<ItemFlag>`, one for flags that needs to be added and one to be removed. Both sets will be read from `item_flags` and the action will be distinguished by a prefix, something like this:
```yaml
item_flags:
- HIDE_ENCHANTMENTS
- remove:HIDE_ATTRIBUTES
# or ~<flag> (or another symbol)
# ! doesn't work because it is used by yaml to specify the type of the value
- ~HIDE_ATTRIBUTES
```

Comment (BlitzOffline) [reply src/main/java/com/extendedclip/deluxemenus/menu/options/MenuItemOptions.java:515]: As I've mentioned, this is not something we really need to deal with right now since we don't actually have a use case for this and that is bcz if `<item_flag_option>: <boolean>` is set to false, we just ignore the option.

Also, I don't think we need to overcomplicate things. We can just rename this method to `addItemFlags` and add a new one to `removeItemFlags`. Especially since the item flags are not held in immutable collections anymore.

Comment (iGabyTM) [reply src/main/java/com/extendedclip/deluxemenus/menu/options/MenuItemOptions.java:515]: By 'remove' you mean `ItemMeta#removeItemFlags`, right?

**Review by Kqliber — APPROVED** [review]
