### PR TITLE
Fixes #187

### LINKED ISSUE #187: [BUG] \n doesn't work in lores when using PAPI placeholders in the lore.
The \n new line code works in lores where you don't have any PAPI placeholders. But if you add a PAPI placeholder to a lore with \n, the lore completely disappears after the placeholder updates.

The recreate the issue, you need to have "update: true". If update is set to false for the item, it will not update the placeholder so the lore will work fine. Enabling update will make the lore disappear after first update if a PAPI placeholder is in the lore.

This is an important issue, as it is a big limitation for the plugin that we can't make flexible lore lines based on PAPI placeholders.

https://github.com/user-attachments/assets/6d7f3dfe-08a7-44f6-b4c6-b918104b29ac

This is the code I used when having the issue for that item:

  'delivery_slot1_standard':
    material: paper
    model_data: 53141
    slot: 18
    update: true
    display_name: '&#EAA44F&lCourier Delivery'
    lore:
      - "&8Delivery Slot #1\n&7Gather and deliver the requested items to complete\n&7the order and earn your payment from the courier.\n&7But act fast — someone else might complete it first!\n\n&#DEB782Type: &fStandard\n&#DEB782Expires:&f%vault_eco_balance%"

### PR DESCRIPTION
**Pull request by BitByLogics**
Simple PR, fixes issue #187 by checking for new lines in item lore and placeholders in update task

### CODE REVIEW

File: src/main/java/com/extendedclip/deluxemenus/menu/MenuHolder.java [hunk 1]
```diff
@@ -278,8 +278,13 @@ public void run() {
                             List<String> updated = new ArrayList<>();
 
                             for (String line : item.options().lore()) {
-                                updated.add(StringUtils
-                                        .color(setPlaceholdersAndArguments(line)));
+                                for(String splitLine : line.split("\n")) {
```
Comment (BlitzOffline) [inline src/main/java/com/extendedclip/deluxemenus/menu/MenuHolder.java:281]: Can we reuse the method MenuItem#getMenuItemLore here? This way, we know for sure that any changes to how lore is parsed in the future, it works the same way for item create and item update.

**Review by BlitzOffline — CHANGES_REQUESTED** [review]

File: src/main/java/com/extendedclip/deluxemenus/menu/MenuHolder.java (hunk 1 above)
Comment (BitByLogics) [reply src/main/java/com/extendedclip/deluxemenus/menu/MenuHolder.java:281]: I could, but I'd have to make the method protected. If that's okay I'll go head and do that.

**Review by BlitzOffline — APPROVED** [review]
