### PR TITLE
fix: item_flags list not being handled

### LINKED ISSUE #110: Multiple flags not working
setting the item flags like this: 
    **item_flags:
    - HIDE_ARMOR_TRIM**
don't work for some reason but when i set like this:
**item_flags: HIDE_ARMOR_TRIM**
works well but can't set more than one flag in that way

### PR DESCRIPTION
**Pull request by iGabyTM**
fix #110

### CODE REVIEW

File: src/main/java/com/extendedclip/deluxemenus/config/DeluxeMenusConfig.java [hunk 1]
```diff
@@ -763,23 +776,25 @@ private Map<Integer, TreeMap<Integer, MenuItem>> loadMenuItems(FileConfiguration
 
             // item flags
             if (c.contains(currentPath + "item_flags")) {
```
Comment (BlitzOffline) [inline src/main/java/com/extendedclip/deluxemenus/config/DeluxeMenusConfig.java:778]: Since this check is handled in getStringListFromConfig, we can remove it from here right?

File: src/main/java/com/extendedclip/deluxemenus/config/DeluxeMenusConfig.java [hunk 2]
```diff
@@ -763,23 +776,25 @@ private Map<Integer, TreeMap<Integer, MenuItem>> loadMenuItems(FileConfiguration
...
-                    String flagAsString = c.getString(currentPath + "item_flags");
-                    ItemFlag flag;
-                    try {
-                        flag = ItemFlag.valueOf(flagAsString.toUpperCase());
-                        builder.itemFlags(Collections.singletonList(flag));
-                    } catch (IllegalArgumentException | NullPointerException ignored) {
+                List<ItemFlag> itemFlags = new ArrayList<>();
+
+                for (String flagAsString : getStringListFromConfig(c, currentPath + "item_flags")) {
+                    ItemFlag flag = Enums.getIfPresent(ItemFlag.class, flagAsString.toUpperCase()).orNull();
```
Comment (BlitzOffline) [inline src/main/java/com/extendedclip/deluxemenus/config/DeluxeMenusConfig.java:782]: Is there a reason to convert to nullable value? why can't we just use the Optional?

**Review by BlitzOffline — APPROVED** [review]

File: src/main/java/com/extendedclip/deluxemenus/config/DeluxeMenusConfig.java (hunk 2 above)
Comment (iGabyTM) [reply src/main/java/com/extendedclip/deluxemenus/config/DeluxeMenusConfig.java:782]: `Enums` uses Google's [`Optional`](https://guava.dev/releases/19.0/api/docs/com/google/common/base/Optional.html) and Java's is already imported in that class and I didn't want to use the full qualifier for the variable _`com.google.common.base.Optional<ItemFlag>`_

File: src/main/java/com/extendedclip/deluxemenus/config/DeluxeMenusConfig.java (hunk 1 above)
Comment (iGabyTM) [reply src/main/java/com/extendedclip/deluxemenus/config/DeluxeMenusConfig.java:778]: 🤷🏼‍♂️ I'd leave it inside `loadMenuItems` too, just to have a visual separation for item flag loading logic

**Review by darbyjack — APPROVED** [review]
